// Generates supabase/seed.sql from lib/demo-data.ts (the same data the unit tests use).
// Run: npm run seed:gen
import { writeFileSync } from "node:fs";
import {
  DEMO_GROUP_ID,
  DEMO_TOKENS,
  demoChecks,
  demoListings,
  demoPeople,
} from "../lib/demo-data.ts";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return `array[${v.map(q).join(", ")}]::text[]`;
  if (typeof v === "object") return `${q(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const lines: string[] = [
  "-- Demo group: Riya, Meera and Kavita + 6 sample listings.",
  "-- GENERATED by `npm run seed:gen` from lib/demo-data.ts. Do not edit by hand.",
  "-- Run AFTER schema.sql. Safe to re-run: it resets the demo group to its original state.",
  "-- Demo links: /g/demo-riya  /g/demo-meera  /g/demo-kavita",
  "",
  `delete from groups where id = ${q(DEMO_GROUP_ID)};`,
  `insert into groups (id, name) values (${q(DEMO_GROUP_ID)}, 'Demo: Riya, Meera & Kavita');`,
  "",
];

demoPeople.forEach((p, i) => {
  lines.push(
    `insert into members (id, group_id, slot, token) values (${q(p.member_id)}, ${q(DEMO_GROUP_ID)}, ${i + 1}, ${q(DEMO_TOKENS[p.member_id])});`,
  );
});
lines.push("");
for (const p of demoPeople) {
  lines.push(
    "insert into constraints (member_id, name, max_rent, no_go_areas, key_locations, lift_required, parking_required, " +
      "pet_friendly_required, min_bathrooms, max_floor_without_lift, nice_to_haves, nice_to_have_other) values (" +
      [
        p.member_id, p.name, p.max_rent, p.no_go_areas, p.key_locations, p.lift_required, p.parking_required,
        p.pet_friendly_required, p.min_bathrooms, p.max_floor_without_lift, p.nice_to_haves, p.nice_to_have_other,
      ]
        .map(q)
        .join(", ") +
      ");",
  );
}
lines.push("");
demoListings.forEach((l, i) => {
  lines.push(
    `insert into listings (id, group_id, added_by, title, url, raw_text, fields, created_at) values (` +
      [l.id, DEMO_GROUP_ID, l.added_by, l.title, l.url, l.raw_text, l.fields].map(q).join(", ") +
      `, now() - interval '${demoListings.length - i} hours');`,
  );
});
lines.push("");
for (const c of demoChecks) {
  lines.push(
    `insert into listing_checks (listing_id, kind, member_id, key, minutes, confirmed) values (` +
      [c.listing_id, c.kind, c.member_id, c.key, c.minutes, c.confirmed].map(q).join(", ") +
      ");",
  );
}

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log("wrote supabase/seed.sql");
